version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - 3000:3000

  web:
    build:
      context: ./web
    volumes:
      - /usr/share/nginx/html/
    ports:
      - 4200:4200
